### ISSUE TITLE
suggestion: remove comments from ends of `_quarto.yml` lines to be added 

### ISSUE THREAD

**Issue by paciorek** [qmd-lab/scheduled-docs#1]
If one copies/pastes the lines to be added to `_quarto.yml` one may want to remove the comments at the end of the line. That's a bit annoying so I suggest the comment about adding all the lines be a single line comment above those lines.

**Comment by andrewpbray** [comment]
Closing this as nothing should needed to be added to `_quarto.yml` now that [metadata extensions](https://quarto.org/docs/extensions/metadata.html) are possible.
