### ISSUE TITLE
failure if no `scheduled-docs` stanza present

### ISSUE THREAD

**Issue by paciorek** [qmd-lab/scheduled-docs#3]
I think that if there is no `scheduled-docs` key, the extension will fail (though I'm playing around with various things, so I might be misunderstanding). Presumably the behavior should be that the extension will do nothing if it doesn't find a stanza to operate on.

**Comment by andrewpbray** [comment]
Fixed in https://github.com/qmd-lab/scheduled-docs/commit/a7e191d7a50844e1574a0c6192965380e4bb1680
